import { redirect } from "next/navigation";
import { Badge, Button, Card, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { getAdminPrincipal } from "@/lib/admin-auth";
import { getAdminAuditEvents, getAdminSessions, getPendingAdminMfa } from "@/lib/admin-identity";
import { changePasswordAction, confirmMfaEnrollmentAction, revokeSessionAction, startMfaEnrollmentAction } from "./actions";

function dateTime(value: string) {
  return new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

export default async function AdminSecurityPage({ searchParams }: { searchParams: Promise<{ updated?: string; error?: string; required?: string }> }) {
  const [principal, params] = await Promise.all([getAdminPrincipal(), searchParams]);
  if (!principal) redirect("/admin/login");
  const sessions = principal.userId ? await getAdminSessions(principal.userId) : [];
  const audit = principal.userId && principal.role === "owner" ? await getAdminAuditEvents(80) : [];
  const pendingMfa = principal.userId && !principal.mfaEnabled ? await getPendingAdminMfa(principal.userId) : null;

  return <Section className="pt-14 md:pt-20"><Container>
    <Button href="/admin" variant="ghost" className="mb-8">Volver al panel</Button>
    <div className="grid gap-6 md:grid-cols-[1fr_0.55fr] md:items-end"><div><Eyebrow>NOAM OS · Seguridad</Eyebrow><Heading as="h1" size="xl">Identidad y sesiones.</Heading></div><div><p className="text-sm leading-7 text-ink/65">Los secretos de sesión no se almacenan. Cada acceso vence a las ocho horas y puede revocarse inmediatamente.</p>{principal.role === "owner" ? <Button href="/admin/security/users" variant="secondary" className="mt-4">Gestionar operadores</Button> : null}</div></div>
    {params.updated ? <p className="mt-8 rounded-sm border border-border bg-panel px-4 py-3 text-sm text-ink/70">{params.updated === "password" ? "Contraseña actualizada y otras sesiones revocadas." : params.updated === "mfa-enabled" ? "MFA quedó activado." : params.updated === "mfa-started" ? "Configuración MFA iniciada. Completa la verificación." : "Sesión revocada."}</p> : null}
    {params.required ? <p className="mt-8 rounded-sm border border-rust/30 bg-rust/[0.06] px-4 py-3 text-sm text-rust">{params.required === "password" ? "Debes reemplazar la contraseña temporal antes de operar." : "Debes activar MFA antes de operar en producción."}</p> : null}
    {params.error ? <p role="alert" className="mt-8 rounded-sm border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800">{params.error === "password-confirmation" ? "La confirmación no coincide." : params.error === "mfa-code" ? "El código MFA no es válido." : params.error === "security-required" ? "Completa el cambio de contraseña y MFA antes de operar." : "No se pudo cambiar la contraseña. Verifica la contraseña actual y la política mínima."}</p> : null}
    <div className="mt-10 grid gap-4 md:grid-cols-4"><Card><p className="text-xs uppercase tracking-[0.12em] text-muted">Operador</p><p className="mt-3 font-medium text-ink">{principal.displayName}</p><p className="mt-1 text-sm text-muted">{principal.email}</p></Card><Card><p className="text-xs uppercase tracking-[0.12em] text-muted">Rol</p><p className="mt-3 text-2xl font-medium text-ink">{principal.role}</p></Card><Card><p className="text-xs uppercase tracking-[0.12em] text-muted">Modo</p><p className="mt-3 text-2xl font-medium text-ink">{principal.authMode}</p></Card><Card><p className="text-xs uppercase tracking-[0.12em] text-muted">MFA</p><p className="mt-3 text-2xl font-medium text-ink">{principal.mfaEnabled ? "Activo" : "Pendiente"}</p></Card></div>

    {principal.authMode === "identity" && !principal.mfaEnabled ? <div className="mt-12 grid gap-8 rounded-md border border-rust/25 bg-rust/[0.04] p-6 md:grid-cols-[0.4fr_1fr]"><div><Eyebrow className="text-rust">Segundo factor</Eyebrow><Heading size="md">Activar MFA.</Heading><p className="mt-3 text-xs leading-6 text-muted">Compatible con Google Authenticator, 1Password, Microsoft Authenticator y otras aplicaciones TOTP.</p></div>{pendingMfa ? <div><p className="text-sm leading-7 text-ink/70">Agrega una cuenta manual e ingresa esta clave. Luego escribe el código de seis dígitos generado por la aplicación.</p><code className="mt-4 block break-all rounded-sm border border-border bg-canvas p-4 text-sm tracking-[0.12em] text-ink">{pendingMfa.secret}</code><details className="mt-3 text-xs text-muted"><summary className="cursor-pointer">URI avanzada</summary><p className="mt-2 break-all">{pendingMfa.uri}</p></details><form action={confirmMfaEnrollmentAction} className="mt-5 flex flex-col gap-3 sm:flex-row"><input name="code" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="000000" className="min-h-11 rounded-sm border border-border bg-canvas px-3 text-sm" /><Button type="submit">Verificar y activar</Button></form></div> : <form action={startMfaEnrollmentAction}><Button type="submit">Comenzar configuración</Button></form>}</div> : null}

    <div className="mt-12 overflow-hidden rounded-md border border-border bg-panel"><div className="border-b border-border px-5 py-4"><h2 className="font-medium text-ink">Sesiones de esta identidad</h2></div><div className="divide-y divide-border">{sessions.length ? sessions.map((session) => {
      const current = session.id === principal.sessionId;
      const active = !session.revokedAt && new Date(session.expiresAt).getTime() > Date.now();
      return <article key={session.id} className="grid gap-4 px-5 py-5 md:grid-cols-[1fr_auto] md:items-center"><div className="flex flex-wrap items-center gap-2"><Badge>{current ? "actual" : active ? "activa" : session.revokedAt ? "revocada" : "vencida"}</Badge><span className="text-sm text-ink/70">Creada {dateTime(session.createdAt)} · última actividad {dateTime(session.lastSeenAt)} · vence {dateTime(session.expiresAt)}</span></div>{active ? <form action={revokeSessionAction}><input type="hidden" name="sessionId" value={session.id} /><Button type="submit" variant="secondary">{current ? "Cerrar esta sesión" : "Revocar"}</Button></form> : null}</article>;
    }) : <p className="px-5 py-8 text-sm text-muted">El modo heredado o de desarrollo no crea sesiones individuales.</p>}</div></div>

    {principal.authMode === "identity" ? <div className="mt-12 grid gap-8 rounded-md border border-border bg-panel p-6 md:grid-cols-[0.4fr_1fr]"><div><Eyebrow>Credencial</Eyebrow><Heading size="md">Cambiar contraseña.</Heading><p className="mt-3 text-xs leading-6 text-muted">Al cambiarla se revocan todas las demás sesiones activas.</p></div><form action={changePasswordAction} className="grid gap-4"><label className="grid gap-2 text-sm font-medium text-ink">Contraseña actual<input name="currentPassword" type="password" required autoComplete="current-password" className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium text-ink">Nueva contraseña<input name="newPassword" type="password" required minLength={14} maxLength={128} autoComplete="new-password" className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label><label className="grid gap-2 text-sm font-medium text-ink">Confirmar<input name="confirmation" type="password" required minLength={14} maxLength={128} autoComplete="new-password" className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label></div><p className="text-xs text-muted">Mínimo 14 caracteres con mayúscula, minúscula, número y símbolo.</p><Button type="submit">Actualizar contraseña</Button></form></div> : null}

    {principal.role === "owner" ? <div className="mt-12 overflow-hidden rounded-md border border-border bg-panel"><div className="border-b border-border px-5 py-4"><h2 className="font-medium text-ink">Bitácora reciente</h2></div><div className="divide-y divide-border">{audit.length ? audit.map((event) => <article key={event.id} className="grid gap-2 px-5 py-4 md:grid-cols-[0.35fr_1fr_auto]"><p className="text-xs text-muted">{event.actorName ?? "Sistema"}</p><p className="text-sm font-medium text-ink">{event.eventType}<span className="ml-2 font-normal text-muted">{event.entityType ?? ""} {event.entityId?.slice(0, 12) ?? ""}</span></p><time className="text-xs text-muted">{dateTime(event.createdAt)}</time></article>) : <p className="px-5 py-8 text-sm text-muted">Todavía no hay eventos.</p>}</div></div> : null}
  </Container></Section>;
}
