import { Activity, ArrowRight, CircleGauge, Droplets, MapPinned, ShieldCheck, Users } from "lucide-react";
import NextLink from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { Accordion, Button, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { breadcrumbJsonLd, buildMetadata, faqJsonLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";

const path = "/analisis-datos-agua-saneamiento";

export const metadata = buildMetadata({
  title: "Análisis de datos para agua y saneamiento",
  description: "Diagnósticos, líneas de base, continuidad, calidad, sostenibilidad rural, inversiones y observatorios de agua y saneamiento en el Perú.",
  path
});

const decisions = [
  { icon: MapPinned, title: "Cerrar brechas con precisión", question: "¿Quién carece de qué servicio, dónde y bajo qué modalidad de prestación?", use: "Diagnóstico territorial, acceso, conexiones, disposición sanitaria, población no servida y cartera priorizada." },
  { icon: Activity, title: "Medir el servicio real", question: "¿La población recibe agua con continuidad, presión, calidad y respuesta ante interrupciones?", use: "Línea de base, desempeño, interrupciones, reclamos, mantenimiento y comparación entre prestadores." },
  { icon: ShieldCheck, title: "Asegurar calidad y salud", question: "¿Qué evidencia permite seguir desinfección, control de calidad y riesgos para la población?", use: "Planes de control, vigilancia, muestreo, alertas, trazabilidad y comunicación de riesgos." },
  { icon: Users, title: "Sostener la prestación rural", question: "¿Qué sistemas, organizaciones comunales y áreas técnicas requieren soporte primero?", use: "DATASS, ATM, organizaciones comunales, operación, cuota familiar, asistencia técnica y reposición." },
  { icon: CircleGauge, title: "Priorizar inversión y resiliencia", question: "¿Qué combinación de obra, mantenimiento, gestión y contingencia mejora el resultado?", use: "Cartera, costos, criticidad, sequía, inundación, continuidad operativa y evaluación de resultados." }
];

const evidenceChain = [
  { number: "01", title: "Fuente", text: "Disponibilidad, cuenca, captación, estacionalidad, riesgo y derecho de uso." },
  { number: "02", title: "Sistema", text: "Infraestructura, capacidad, estado, operación, mantenimiento y vulnerabilidad." },
  { number: "03", title: "Calidad", text: "Parámetros, punto, fecha, método, desinfección, laboratorio y control." },
  { number: "04", title: "Prestación", text: "Cobertura, continuidad, presión, interrupciones, atención y confiabilidad." },
  { number: "05", title: "Personas", text: "Acceso efectivo, uso, asequibilidad, satisfacción y población desatendida." },
  { number: "06", title: "Sostenibilidad", text: "Gestión, ingresos, costos, asistencia, reposición, ambiente y resiliencia." }
];

const evidence = [
  { label: "Fuente oficial", title: "DATASS rural", text: "Diagnóstico de sistemas y prestadores rurales con actualización a cargo de gobiernos regionales y locales.", href: "https://datass.vivienda.gob.pe/" },
  { label: "TDR + plantilla", title: "Contratar el análisis", text: "Veinte bloques para definir brecha, servicio, calidad, operación, inversión y aceptación.", href: "/toolkits/tdr-analisis-agua-saneamiento" },
  { label: "Territorio", title: "Perfiles municipales", text: "Contexto, población, capacidad, proyectos e indicadores para delimitar el encargo.", href: "/dataperu/municipios" },
  { label: "Sistema", title: "Observatorios y tableros", text: "Indicadores, alertas, responsables, actualización y transferencia institucional.", href: "/observatorios-dashboards-visores" },
  { label: "Riesgo", title: "Gestión del riesgo", text: "Escenarios, activos críticos, continuidad, respuesta y recuperación del servicio.", href: "/analisis-datos-gestion-riesgo-desastres" },
  { label: "Evaluación", title: "Línea de base y resultados", text: "Diseños para saber si una intervención mejoró acceso, calidad o sostenibilidad.", href: "/linea-base-evaluacion-impacto" }
];

const faq = [
  { title: "¿Pueden diagnosticar agua y saneamiento rural?", content: "Sí. El alcance puede integrar DATASS, información de ATM y organizaciones comunales, infraestructura, calidad, continuidad, gestión, asistencia técnica y trabajo de campo. La actualización administrativa no reemplaza la verificación del sistema ni de la prestación." },
  { title: "¿Una conexión demuestra acceso a agua segura?", content: "No. Una conexión o cobertura registrada debe analizarse junto con continuidad, presión, calidad, asequibilidad, uso y respuesta ante fallas. Cada indicador responde una pregunta distinta." },
  { title: "¿Pueden crear un observatorio de agua y saneamiento?", content: "Sí. Primero se definen decisiones, usuarios, prestadores, indicadores, alertas, fuentes, frecuencia y responsables. El tablero debe incluir reglas de calidad, protocolos y una rutina de gestión, no solo gráficos." },
  { title: "¿Pueden priorizar proyectos o mantenimiento?", content: "Sí. Podemos integrar brechas, población, criticidad, estado de activos, riesgos, costos, madurez y capacidad de operación. La priorización debe mostrar supuestos y no sustituye la formulación ni la evaluación técnica de inversiones." },
  { title: "¿Pueden analizar calidad del agua?", content: "Podemos diseñar la estructura analítica, integrar resultados y construir alertas si la información documenta punto, fecha, parámetro, método, unidad, laboratorio y control de calidad. No sustituimos muestreo especializado, vigilancia sanitaria ni ensayos acreditados." },
  { title: "¿Trabajan con prestadores y empresas?", content: "Sí. El trabajo puede cubrir desempeño, interrupciones, reclamos, activos, sostenibilidad financiera, riesgo, experiencia del usuario y descargas no domésticas. El alcance respeta las competencias del regulador y de las autoridades sectoriales." }
];

export default function WaterSanitationDataPage() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd([{ name: "Inicio", path: "/" }, { name: "Análisis de datos para agua y saneamiento", path }])} />
      <JsonLd data={faqJsonLd(faq)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Service", name: "Análisis de datos para agua y saneamiento", description: "Diagnósticos, líneas de base, observatorios y evaluación de servicios de agua y saneamiento para gobiernos y prestadores.", url: `${siteConfig.url}${path}`, provider: { "@type": "Organization", name: "NOAM", url: siteConfig.url }, areaServed: { "@type": "Country", name: "Perú" } }} />

      <section className="overflow-hidden bg-[#18333a] pb-16 pt-14 text-white md:pb-24 md:pt-20"><Container><div className="grid gap-12 lg:grid-cols-[1fr_0.46fr] lg:items-end lg:gap-20"><div><Eyebrow className="text-[#9dcbd0]">Agua, servicio y territorio</Eyebrow><Heading as="h1" size="display" className="max-w-[15ch] text-white">Una conexión registrada no demuestra agua segura ni servicio continuo.</Heading></div><div><p className="text-base leading-8 text-white/68">Conectamos fuentes, sistemas, calidad, prestación, personas y sostenibilidad para decidir dónde intervenir y cómo medir la mejora.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="#decisiones" variant="secondary" className="rounded-full border-white bg-white text-ink">Definir la necesidad</Button><Button href="/toolkits/tdr-analisis-agua-saneamiento" variant="ghost" className="!text-white/70 hover:!text-white">Abrir TDR y plantilla</Button></div></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-md border border-white/12 bg-white/12 sm:grid-cols-3">{["Gobiernos, prestadores y población", "Acceso, calidad y continuidad", "Datos oficiales, operación y campo"].map((item, index) => <div key={item} className="bg-[#20434a] p-6 md:p-8"><span className="font-mono text-[10px] text-[#9dcbd0]">0{index + 1}</span><p className="mt-9 max-w-[27ch] text-lg font-medium leading-6 tracking-[-0.02em] text-white/86">{item}</p></div>)}</div></Container></section>

      <Section id="decisiones"><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Qué necesitas decidir</Eyebrow><Heading size="xl">Cinco decisiones que una cifra de cobertura no resuelve.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">El análisis debe distinguir infraestructura instalada, prestación efectiva y resultado para las personas.</p></div><div className="mt-12 divide-y divide-border border-y border-border">{decisions.map(({ icon: Icon, title, question, use }, index) => <article key={title} className="grid gap-6 py-9 md:grid-cols-[64px_0.75fr_1fr] md:gap-10 md:py-11"><div className="flex items-center gap-4 md:block"><span className="font-mono text-[10px] text-[#397d86]">0{index + 1}</span><Icon className="h-5 w-5 text-[#397d86] md:mt-8" aria-hidden /></div><div><h2 className="text-2xl font-medium tracking-[-0.035em] text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/72">{question}</p></div><div><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">Aplicaciones</span><p className="mt-3 text-sm leading-7 text-ink/62">{use}</p></div></article>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-20"><div><Droplets className="h-5 w-5 text-[#397d86]" aria-hidden /><Eyebrow className="mt-6">Cadena de evidencia</Eyebrow><Heading size="xl">De la fuente al servicio sostenible.</Heading><p className="mt-5 text-sm leading-7 text-ink/65">La cadena evita llamar brecha, falla o logro a observaciones que miden cosas distintas.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{evidenceChain.map((item) => <article key={item.number} className="min-h-[190px] bg-canvas p-6 md:p-8"><span className="font-mono text-[10px] text-[#397d86]">{item.number}</span><h2 className="mt-9 text-xl font-medium tracking-[-0.025em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p></article>)}</div></div></Container></Section>

      <Section className="border-b border-border bg-[#e2edef]"><Container><div className="grid gap-10 lg:grid-cols-[0.46fr_1fr] lg:gap-20"><div><Eyebrow>Marco y fuentes</Eyebrow><Heading size="xl">Una sola base no describe toda la prestación.</Heading></div><div className="max-w-3xl space-y-5 text-base leading-8 text-ink/72"><p>DATASS organiza el diagnóstico rural y asigna a gobiernos regionales y locales la actualización de la información. SUNASS publica benchmarking, indicadores e interrupciones de prestadores; ANA integra información hídrica; INEI aporta mediciones de hogares. La pregunta determina qué fuentes pueden combinarse.</p><p>Los registros administrativos no corrigen por sí solos desactualización, diferencias de ámbito, sistemas sin georreferencia, población dispersa ni resultados de laboratorio incomparables. Cada dato debe conservar fuente, fecha, unidad, cobertura y límite.</p><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#2f7078]"><a href="https://datass.vivienda.gob.pe/" target="_blank" rel="noreferrer">DATASS</a><a href="https://www.gob.pe/institucion/sunass/colecciones/27838benchmarking-regulatorio-sunass" target="_blank" rel="noreferrer">Benchmarking SUNASS</a><a href="https://www.datosabiertos.gob.pe/group/superintendencia-nacional-de-servicios-y-saneamiento-sunass" target="_blank" rel="noreferrer">Datos abiertos SUNASS</a><a href="https://www.gob.pe/institucion/ana/noticias/828913-ana-presenta-moderna-herramienta-tecnologica-observatorio-nacional-de-recursos-hidricos-para-la-gestion-integrada-de-recursos-hidricos" target="_blank" rel="noreferrer">Observatorio ANA</a><a href="https://proyectos.inei.gob.pe/iinei/srienaho/Descarga/DocumentosMetodologicos/2024-18/26_Resultados_Programas_Presupuestales_2024.pdf" target="_blank" rel="noreferrer">Indicadores INEI</a></div></div></div></Container></Section>

      <Section><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Evidencia y servicios</Eyebrow><Heading size="xl">Explora antes de plantear el encargo.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Revisa fuentes, contexto territorial, método, sistemas y evaluación que pueden combinarse según la decisión.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{evidence.map((item) => <NextLink key={item.href} href={item.href} className="group min-h-[225px] bg-canvas p-6 transition-colors hover:bg-panel md:p-8" {...(item.href.startsWith("http") ? { target: "_blank", rel: "noreferrer" } : {})}><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#397d86]">{item.label}</span><h2 className="mt-10 text-2xl font-medium tracking-[-0.035em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-ink">Abrir <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" aria-hidden /></span></NextLink>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container size="narrow"><Eyebrow>Preguntas frecuentes</Eyebrow><Heading size="xl">Antes de medir o construir.</Heading><Accordion items={faq} className="mt-8" /></Container></Section>

      <Section className="pb-0"><Container><div className="relative overflow-hidden rounded-[1.5rem] bg-[#2f7078] px-7 py-12 text-white md:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[56px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><Eyebrow className="text-white/55">Primera definición</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-medium leading-tight tracking-[-0.045em] md:text-5xl">Cuéntanos qué servicio, población o territorio debe mejorar y qué decisión está pendiente.</h2></div><div className="flex flex-wrap gap-3"><Button href="/diagnostico?from=/analisis-datos-agua-saneamiento" analyticsEvent="cta_click" analyticsTarget="water-sanitation-hub:scope" variant="secondary" className="rounded-full border-white bg-white text-ink">Diseñar un alcance</Button><Button href="/contact?interest=agua-saneamiento&from=/analisis-datos-agua-saneamiento" analyticsEvent="cta_click" analyticsTarget="water-sanitation-hub:contact" variant="ghost" className="!text-white/70 hover:!text-white">Plantear el encargo</Button></div></div></div></Container></Section>
    </>
  );
}
