import { ArrowRight, BriefcaseBusiness, Building2, ChartNoAxesCombined, MapPinned, Network, UsersRound } from "lucide-react";
import NextLink from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { Accordion, Button, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { breadcrumbJsonLd, buildMetadata, faqJsonLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";

const path = "/analisis-datos-desarrollo-economico-local";

export const metadata = buildMetadata({
  title: "Análisis de datos para desarrollo económico local",
  description: "Diagnósticos productivos, empleo, cadenas de valor, mercados y sistemas de seguimiento para gobiernos regionales, municipalidades, empresas y organizaciones productivas.",
  path
});

const decisions = [
  { icon: ChartNoAxesCombined, title: "Comprender la estructura productiva", question: "¿Qué actividades, empresas, empleo y flujos sostienen la economía del territorio?", use: "Diagnóstico económico, línea de base, tejido empresarial, especialización y dinámica territorial." },
  { icon: Building2, title: "Reducir fricciones", question: "¿Qué barreras limitan formalización, inversión, operación o acceso a servicios?", use: "Licencias, trámites, infraestructura, mercados, financiamiento, asistencia y coordinación pública." },
  { icon: Network, title: "Priorizar cadenas y sectores", question: "¿Dónde coinciden capacidad productiva, comprador, logística y posibilidad real de capturar valor?", use: "Cadenas de valor, proveedores, clústeres, PROCOMPITE, diversificación y desarrollo productivo." },
  { icon: UsersRound, title: "Conectar empleo y capacidades", question: "¿Qué demanda ocupacional existe y qué grupos enfrentan las mayores brechas de acceso?", use: "Empleabilidad, formación pertinente, inclusión, intermediación y necesidades empresariales." },
  { icon: MapPinned, title: "Conducir y evaluar la agenda", question: "¿Qué intervención produce qué resultado, en qué territorio y con qué evidencia?", use: "Cartera priorizada, tablero, metas, evaluación de servicios y aprendizaje institucional." }
];

const evidenceChain = [
  { number: "01", title: "Decisión", text: "Problema público, productivo o de inversión que debe reducirse." },
  { number: "02", title: "Unidad", text: "Empresa, empleo, cadena, mercado, población, territorio y periodo pertinentes." },
  { number: "03", title: "Fuentes", text: "Registros, estadísticas, datos operativos, encuestas, entrevistas y campo." },
  { number: "04", title: "Fricción", text: "Costo, capacidad, infraestructura, información, coordinación o acceso que limita el resultado." },
  { number: "05", title: "Oportunidad", text: "Demanda, comprador, volumen, margen, empleo y condiciones necesarias para sostenerla." },
  { number: "06", title: "Resultado", text: "Cambio verificable, responsable, plazo, indicador y evidencia de aprendizaje." }
];

const evidence = [
  { label: "Datos municipales", title: "Desarrollo económico en DataPerú", text: "Licencias y acciones municipales declaradas en RENAMU 2025.", href: "/dataperu/temas/desarrollo-economico" },
  { label: "TDR + plantilla", title: "Contratar el análisis", text: "Estructura productiva, empleo, mercados, barreras y aceptación verificable.", href: "/toolkits/tdr-analisis-desarrollo-economico-local" },
  { label: "Mercado", title: "Inteligencia territorial", text: "Demanda, clientes, sectores, localización y validación antes de invertir.", href: "/estudios-mercado-inteligencia-territorial" },
  { label: "Territorios", title: "Perfiles departamentales", text: "Problemas, oportunidades, intervenciones y vacíos de evidencia por departamento.", href: "/dataperu/departamentos" },
  { label: "Prácticas", title: "Decisiones para empresas", text: "Industrias, entorno territorial, proveedores, inversión e impacto.", href: "/sectors/companies" },
  { label: "Solución", title: "Inteligencia para inversión", text: "Perfiles, comparadores, escenarios y recomendación ejecutiva.", href: "/solutions/inteligencia-territorial-inversion" }
];

const faq = [
  { title: "¿Pueden preparar una agenda para una municipalidad pequeña?", content: "Sí. El alcance se ajusta a las competencias, recursos y decisiones reales de la entidad. Puede comenzar con fuentes oficiales, entrevistas y una cartera corta antes de desarrollar estudios o sistemas más amplios." },
  { title: "¿El análisis indica qué producto o sector conviene impulsar?", content: "Puede comparar alternativas, pero una oportunidad no se valida solo por potencial productivo. Debe comprobar demanda, comprador, volumen, calidad, logística, costos, gobernanza y distribución del beneficio." },
  { title: "¿Más licencias significan mayor desarrollo económico?", content: "No necesariamente. Las licencias emitidas describen una actividad administrativa y no equivalen al stock de empresas activas, formalización, empleo, productividad, supervivencia empresarial ni impacto de la gestión." },
  { title: "¿Pueden incluir encuestas, entrevistas o trabajo de campo?", content: "Sí. Se incorporan cuando resuelven vacíos capaces de cambiar la decisión: demanda, barreras, experiencia del usuario, relaciones de cadena, capacidades empresariales o condiciones de una localización." },
  { title: "¿Trabajan cadenas de valor y proveedores locales?", content: "Sí. El estudio puede reconstruir actores, flujos, compras, requisitos, márgenes, cuellos de botella y oportunidades de articulación. La recomendación debe partir de demanda verificable y no solo de una lista de productores." },
  { title: "¿Pueden evaluar una feria, capacitación o programa productivo?", content: "Sí. Debe definirse el resultado esperado y una comparación pertinente. Participantes, eventos o presupuesto ejecutado son productos de gestión; no demuestran por sí solos ventas, empleo, productividad o sostenibilidad." }
];

export default function LocalEconomicDevelopmentDataPage() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd([{ name: "Inicio", path: "/" }, { name: "Análisis de datos para desarrollo económico local", path }])} />
      <JsonLd data={faqJsonLd(faq)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Service", name: "Análisis de datos para desarrollo económico local", description: "Diagnósticos productivos, empleo, cadenas de valor, mercados y sistemas de seguimiento para gobiernos y empresas.", url: `${siteConfig.url}${path}`, provider: { "@type": "Organization", name: "NOAM", url: siteConfig.url }, areaServed: { "@type": "Country", name: "Perú" } }} />

      <section className="overflow-hidden bg-[#25241f] pb-16 pt-14 text-white md:pb-24 md:pt-20"><Container><div className="grid gap-12 lg:grid-cols-[1fr_0.46fr] lg:items-end lg:gap-20"><div><Eyebrow className="text-[#d6c99b]">Economía local, empleo y territorio</Eyebrow><Heading as="h1" size="display" className="max-w-[16ch] text-white">Una feria o una licencia emitida no demuestran desarrollo económico.</Heading></div><div><p className="text-base leading-8 text-white/68">Conectamos tejido productivo, empleo, demanda, mercados, infraestructura y acción pública para decidir dónde reducir barreras y cómo crear resultados verificables.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="#decisiones" variant="secondary" className="rounded-full border-white bg-white text-ink">Definir la necesidad</Button><Button href="/toolkits/tdr-analisis-desarrollo-economico-local" variant="ghost" className="!text-white/70 hover:!text-white">Abrir TDR y plantilla</Button></div></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-md border border-white/12 bg-white/12 sm:grid-cols-3">{["Gobiernos, empresas y organizaciones", "Empleo, cadenas y acceso a mercados", "Fuentes oficiales, datos propios y campo"].map((item, index) => <div key={item} className="bg-[#302f29] p-6 md:p-8"><span className="font-mono text-[10px] text-[#d6c99b]">0{index + 1}</span><p className="mt-9 max-w-[27ch] text-lg font-medium leading-6 tracking-[-0.02em] text-white/86">{item}</p></div>)}</div></Container></section>

      <Section id="decisiones"><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Qué necesitas decidir</Eyebrow><Heading size="xl">Cinco preguntas para pasar de actividades a resultados.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Capacitar, organizar una feria o simplificar un trámite puede ser útil. Su valor depende de la barrera que resuelve, la población alcanzada y el cambio económico que puede verificarse.</p></div><div className="mt-12 divide-y divide-border border-y border-border">{decisions.map(({ icon: Icon, title, question, use }, index) => <article key={title} className="grid gap-6 py-9 md:grid-cols-[64px_0.75fr_1fr] md:gap-10 md:py-11"><div className="flex items-center gap-4 md:block"><span className="font-mono text-[10px] text-[#806d32]">0{index + 1}</span><Icon className="h-5 w-5 text-[#806d32] md:mt-8" aria-hidden /></div><div><h2 className="text-2xl font-medium tracking-[-0.035em] text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/72">{question}</p></div><div><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">Aplicaciones</span><p className="mt-3 text-sm leading-7 text-ink/62">{use}</p></div></article>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-20"><div><BriefcaseBusiness className="h-5 w-5 text-[#806d32]" aria-hidden /><Eyebrow className="mt-6">Cadena de evidencia</Eyebrow><Heading size="xl">De la oportunidad aparente al resultado defendible.</Heading><p className="mt-5 text-sm leading-7 text-ink/65">La recomendación debe conservar el vínculo entre problema, fuente, territorio, barrera, oportunidad e intervención.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{evidenceChain.map((item) => <article key={item.number} className="min-h-[190px] bg-canvas p-6 md:p-8"><span className="font-mono text-[10px] text-[#806d32]">{item.number}</span><h2 className="mt-9 text-xl font-medium tracking-[-0.025em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p></article>)}</div></div></Container></Section>

      <Section className="border-b border-border bg-[#ebe7d8]"><Container><div className="grid gap-10 lg:grid-cols-[0.46fr_1fr] lg:gap-20"><div><Eyebrow>Marco y fuentes</Eyebrow><Heading size="xl">Una agenda local necesita fuentes empresariales, laborales y territoriales.</Heading></div><div className="max-w-3xl space-y-5 text-base leading-8 text-ink/72"><p>La Ley Orgánica de Municipalidades vincula el desarrollo económico local con la micro y pequeña empresa, las capacidades y la equidad. INEI observa demografía empresarial; PRODUCE publica estadísticas Mipyme y sectoriales; MTPE integra empleo, demanda ocupacional y formalización; PROMPERÚ ofrece inteligencia para oportunidades de inversión.</p><p>DataPerú añade licencias y acciones declaradas por municipalidades en RENAMU 2025. Esas variables describen gestión reportada: no miden por sí solas empresas activas, informalidad, empleo, ingresos, productividad ni impacto.</p><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#6f5e2b]"><a href="https://www.gob.pe/90950-gobierno-local-y-desarrollo-local" target="_blank" rel="noreferrer">Competencia municipal</a><a href="https://www.inei.gob.pe/biblioteca-virtual/boletines/demografia-empresarial-8237/1/" target="_blank" rel="noreferrer">Demografía empresarial</a><a href="https://ogeiee.produce.gob.pe/index.php/shortcode/oee-documentos-publicaciones/publicaciones-anuales" target="_blank" rel="noreferrer">Estadísticas de PRODUCE</a><a href="https://www.gob.pe/institucion/mtpe/campa%C3%B1as/18520-observatorio-laboral" target="_blank" rel="noreferrer">Observatorio Laboral</a><a href="https://www.promperu.gob.pe/investdata" target="_blank" rel="noreferrer">InvestData</a><NextLink href="/dataperu/temas/desarrollo-economico">Capacidades en DataPerú</NextLink></div></div></div></Container></Section>

      <Section><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Evidencia y servicios</Eyebrow><Heading size="xl">Explora antes de plantear el encargo.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Revisa datos municipales, agendas departamentales, método y soluciones para gobiernos, empresas y organizaciones productivas.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{evidence.map((item) => <NextLink key={item.href} href={item.href} className="group min-h-[225px] bg-canvas p-6 transition-colors hover:bg-panel md:p-8"><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#806d32]">{item.label}</span><h2 className="mt-10 text-2xl font-medium tracking-[-0.035em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-ink">Abrir <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" aria-hidden /></span></NextLink>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container size="narrow"><Eyebrow>Preguntas frecuentes</Eyebrow><Heading size="xl">Antes de impulsar otra actividad.</Heading><Accordion items={faq} className="mt-8" /></Container></Section>

      <Section className="pb-0"><Container><div className="relative overflow-hidden rounded-[1.5rem] bg-[#806d32] px-7 py-12 text-white md:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[56px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><Eyebrow className="text-white/55">Primera definición</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-medium leading-tight tracking-[-0.045em] md:text-5xl">Cuéntanos qué economía territorial quieres comprender y qué decisión debe cambiar.</h2></div><div className="flex flex-wrap gap-3"><Button href="/diagnostico?from=/analisis-datos-desarrollo-economico-local" analyticsEvent="cta_click" analyticsTarget="local-economy-hub:scope" variant="secondary" className="rounded-full border-white bg-white text-ink">Diseñar un alcance</Button><Button href="/contact?interest=desarrollo-economico-local&from=/analisis-datos-desarrollo-economico-local" analyticsEvent="cta_click" analyticsTarget="local-economy-hub:contact" variant="ghost" className="!text-white/70 hover:!text-white">Plantear el encargo</Button></div></div></div></Container></Section>
    </>
  );
}
