import { ArrowRight, ClipboardCheck, HeartHandshake, MapPinned, Network, ScanSearch, ShieldCheck } from "lucide-react";
import NextLink from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { Accordion, Button, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { breadcrumbJsonLd, buildMetadata, faqJsonLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";

const path = "/analisis-datos-politicas-sociales";

export const metadata = buildMetadata({
  title: "Análisis de datos para políticas y programas sociales",
  description: "Diagnósticos, focalización, líneas de base, seguimiento y evaluación de políticas, programas y servicios para población vulnerable en el Perú.",
  path
});

const decisions = [
  { icon: ScanSearch, title: "Comprender necesidades", question: "¿Qué privación, barrera o riesgo afecta a qué población, dónde y en qué etapa de vida?", use: "Diagnóstico social, pobreza, primera infancia, cuidados, discapacidad, personas mayores y territorio." },
  { icon: MapPinned, title: "Encontrar brechas de atención", question: "¿Quién cumple criterios, quién accede, quién queda fuera y por qué?", use: "Focalización, demanda no atendida, cobertura efectiva, accesibilidad y errores de inclusión o exclusión." },
  { icon: ClipboardCheck, title: "Seguir la prestación", question: "¿El servicio llegó a tiempo, con calidad y según el diseño previsto?", use: "Padrones, atenciones, visitas, transferencias, insumos, calidad, reclamos y fidelidad de implementación." },
  { icon: Network, title: "Articular respuestas", question: "¿Qué institución debe actuar cuando una necesidad atraviesa varios servicios?", use: "Rutas de atención, derivaciones, interoperabilidad, alertas, gestión de casos y coordinación territorial." },
  { icon: HeartHandshake, title: "Evaluar resultados", question: "¿Qué cambió, para quién, dónde y qué parte puede atribuirse a la intervención?", use: "Teoría de cambio, línea de base, proceso, resultados, impacto, costos y decisiones de mejora." }
];

const evidenceChain = [
  { number: "01", title: "Persona", text: "Población, hogar, etapa de vida, identidad, territorio y salvaguardas." },
  { number: "02", title: "Necesidad", text: "Privación, riesgo, barrera, severidad, duración y demanda expresada o latente." },
  { number: "03", title: "Elegibilidad", text: "Criterio, fuente, vigencia, actualización, excepción y mecanismo de revisión." },
  { number: "04", title: "Acceso", text: "Conocimiento, solicitud, espera, desplazamiento, costo, abandono y exclusión." },
  { number: "05", title: "Prestación", text: "Servicio recibido, oportunidad, intensidad, calidad, continuidad y experiencia." },
  { number: "06", title: "Resultado", text: "Cambio en bienestar, capacidades, protección, autonomía y desigualdad." }
];

const evidence = [
  { label: "Datos territoriales", title: "Geoportal MIDIS", text: "Centros poblados, cobertura, intervenciones y brechas para análisis territorial.", href: "https://www.gob.pe/institucion/midis/campa%C3%B1as/142197-geoportal-midis" },
  { label: "TDR + plantilla", title: "Contratar el análisis", text: "Veinte bloques para necesidades, focalización, prestación, articulación y evaluación.", href: "/toolkits/tdr-analisis-politicas-sociales" },
  { label: "Evaluación", title: "Línea de base y resultados", text: "Métodos para programas, proyectos y políticas con preguntas e inferencias defendibles.", href: "/linea-base-evaluacion-impacto" },
  { label: "Escucha", title: "Encuestas y experiencia", text: "Necesidades, barreras, satisfacción y voz de usuarios con diseño muestral explícito.", href: "/encuestas-estudios-opinion" },
  { label: "Territorio", title: "Agendas departamentales", text: "Problemas, poblaciones desatendidas, oportunidades y vacíos de evidencia.", href: "/dataperu/departamentos" },
  { label: "Sistema", title: "Observatorios y alertas", text: "Indicadores, protocolos, responsables, actualización y operación institucional.", href: "/observatorios-dashboards-visores" }
];

const faq = [
  { title: "¿Pueden diagnosticar una brecha social en un distrito o región?", content: "Sí. Delimitamos población, necesidad, territorio, servicios, cobertura, barreras, capacidades y fuentes. La síntesis diferencia datos observados, estimaciones, registros administrativos y vacíos que requieren escucha o trabajo de campo." },
  { title: "¿Estar en un padrón demuestra que una persona fue atendida?", content: "No. Elegibilidad, afiliación, programación, prestación efectiva y resultado son etapas distintas. El análisis debe seguir transiciones, tiempos, abandono, duplicidad y exclusión sin exponer información personal." },
  { title: "¿Pueden mejorar focalización o cobertura?", content: "Podemos analizar criterios, fuentes, actualización, brechas territoriales, accesibilidad y errores operativos. La entidad competente conserva la clasificación, elegibilidad y decisión administrativa, así como los canales de revisión y reclamo." },
  { title: "¿Pueden crear un observatorio social?", content: "Sí. Debe comenzar por decisiones, usuarios, indicadores, alertas, protocolos y responsables. La publicación usa agregación y reglas de divulgación; los datos nominales requieren controles de acceso, finalidad y trazabilidad." },
  { title: "¿Pueden evaluar un programa o política?", content: "Sí. Primero verificamos teoría de cambio, preguntas, implementación, calidad de datos y alternativas de comparación. No toda intervención permite estimar impacto causal, pero puede evaluarse diseño, proceso, resultados, equidad o costo." },
  { title: "¿Usan IA para priorizar personas?", content: "No recomendamos decisiones automatizadas opacas sobre acceso a derechos. La IA puede apoyar tareas controladas, pero la focalización de alto impacto exige base legal, calidad, explicabilidad, supervisión humana, apelación y evaluación de sesgos." }
];

export default function SocialPolicyDataPage() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd([{ name: "Inicio", path: "/" }, { name: "Análisis de datos para políticas sociales", path }])} />
      <JsonLd data={faqJsonLd(faq)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Service", name: "Análisis de datos para políticas y programas sociales", description: "Diagnósticos, seguimiento y evaluación de políticas, programas y servicios para población vulnerable.", url: `${siteConfig.url}${path}`, provider: { "@type": "Organization", name: "NOAM", url: siteConfig.url }, areaServed: { "@type": "Country", name: "Perú" } }} />

      <section className="overflow-hidden bg-[#382d32] pb-16 pt-14 text-white md:pb-24 md:pt-20"><Container><div className="grid gap-12 lg:grid-cols-[1fr_0.46fr] lg:items-end lg:gap-20"><div><Eyebrow className="text-[#d8b9c5]">Personas, servicios y resultados</Eyebrow><Heading as="h1" size="display" className="max-w-[15ch] text-white">Estar en un padrón no demuestra que una necesidad fue atendida.</Heading></div><div><p className="text-base leading-8 text-white/68">Conectamos necesidades, elegibilidad, acceso, prestación y resultados para encontrar brechas y mejorar políticas sin perder de vista a las personas.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="#decisiones" variant="secondary" className="rounded-full border-white bg-white text-ink">Definir la necesidad</Button><Button href="/toolkits/tdr-analisis-politicas-sociales" variant="ghost" className="!text-white/70 hover:!text-white">Abrir TDR y plantilla</Button></div></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-md border border-white/12 bg-white/12 sm:grid-cols-3">{["Gobiernos, programas y servicios", "Cobertura, calidad y resultados", "Datos protegidos, escucha y territorio"].map((item, index) => <div key={item} className="bg-[#493b42] p-6 md:p-8"><span className="font-mono text-[10px] text-[#d8b9c5]">0{index + 1}</span><p className="mt-9 max-w-[27ch] text-lg font-medium leading-6 tracking-[-0.02em] text-white/86">{item}</p></div>)}</div></Container></section>

      <Section id="decisiones"><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Qué necesitas decidir</Eyebrow><Heading size="xl">Cinco decisiones que una cifra de cobertura no resuelve.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">La gestión social debe distinguir a quién se identifica, quién accede, qué recibe y qué cambia.</p></div><div className="mt-12 divide-y divide-border border-y border-border">{decisions.map(({ icon: Icon, title, question, use }, index) => <article key={title} className="grid gap-6 py-9 md:grid-cols-[64px_0.75fr_1fr] md:gap-10 md:py-11"><div className="flex items-center gap-4 md:block"><span className="font-mono text-[10px] text-[#8b5368]">0{index + 1}</span><Icon className="h-5 w-5 text-[#8b5368] md:mt-8" aria-hidden /></div><div><h2 className="text-2xl font-medium tracking-[-0.035em] text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/72">{question}</p></div><div><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">Aplicaciones</span><p className="mt-3 text-sm leading-7 text-ink/62">{use}</p></div></article>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-20"><div><ShieldCheck className="h-5 w-5 text-[#8b5368]" aria-hidden /><Eyebrow className="mt-6">Cadena de evidencia</Eyebrow><Heading size="xl">De la necesidad al cambio en bienestar.</Heading><p className="mt-5 text-sm leading-7 text-ink/65">La cadena hace visibles exclusiones y pérdidas entre identificación, acceso y prestación.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{evidenceChain.map((item) => <article key={item.number} className="min-h-[190px] bg-canvas p-6 md:p-8"><span className="font-mono text-[10px] text-[#8b5368]">{item.number}</span><h2 className="mt-9 text-xl font-medium tracking-[-0.025em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p></article>)}</div></div></Container></Section>

      <Section className="border-b border-border bg-[#efe6e9]"><Container><div className="grid gap-10 lg:grid-cols-[0.46fr_1fr] lg:gap-20"><div><Eyebrow>Marco y fuentes</Eyebrow><Heading size="xl">La información social debe ser útil sin volver vulnerables a las personas.</Heading></div><div className="max-w-3xl space-y-5 text-base leading-8 text-ink/72"><p>El Geoportal MIDIS integra centros poblados, intervenciones y cobertura territorial. La Plataforma Nacional de Datos Abiertos publica cobertura distrital de programas; GeoSISFOH apoya el análisis de focalización; INEI aporta pobreza y condiciones de vida; Evidencia MIDIS reúne estudios y evaluaciones.</p><p>Los cruces nominales, mapas finos y modelos predictivos pueden generar exposición, discriminación o decisiones injustas. El alcance debe aplicar minimización, finalidad, seguridad, agregación, revisión humana y mecanismos de corrección.</p><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#7c4c5d]"><a href="https://www.gob.pe/institucion/midis/campa%C3%B1as/142197-geoportal-midis" target="_blank" rel="noreferrer">Geoportal MIDIS</a><a href="https://www.datosabiertos.gob.pe/dataset/cobertura-de-los-programas-sociales-adscritos-al-midis-ministerio-de-desarrollo-e-inclusi%C3%B3n" target="_blank" rel="noreferrer">Cobertura de programas</a><a href="https://www.gob.pe/institucion/midis/noticias/1400923-midis-presenta-geosisfoh-para-fortalecer-la-focalizacion-y-mejorar-la-atencion-de-la-poblacion-vulnerable" target="_blank" rel="noreferrer">GeoSISFOH</a><a href="https://www.inei.gob.pe/media/difusion/app/files/basic-html/page12.html" target="_blank" rel="noreferrer">Publicaciones INEI 2026</a><a href="https://www.gob.pe/institucion/midis/noticias/616046-midis-comparte-experiencias-de-monitoreo-y-evaluacion-de-las-politicas-de-desarrollo-e-inclusion-social-basadas-en-evidencias" target="_blank" rel="noreferrer">Evidencia MIDIS</a></div></div></div></Container></Section>

      <Section><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Evidencia y servicios</Eyebrow><Heading size="xl">Explora antes de plantear el encargo.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Combina fuentes territoriales, método de evaluación, escucha y sistemas según la política o población.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{evidence.map((item) => <NextLink key={item.href} href={item.href} className="group min-h-[225px] bg-canvas p-6 transition-colors hover:bg-panel md:p-8" {...(item.href.startsWith("http") ? { target: "_blank", rel: "noreferrer" } : {})}><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#8b5368]">{item.label}</span><h2 className="mt-10 text-2xl font-medium tracking-[-0.035em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-ink">Abrir <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" aria-hidden /></span></NextLink>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container size="narrow"><Eyebrow>Preguntas frecuentes</Eyebrow><Heading size="xl">Antes de usar un padrón o modelo.</Heading><Accordion items={faq} className="mt-8" /></Container></Section>

      <Section className="pb-0"><Container><div className="relative overflow-hidden rounded-[1.5rem] bg-[#7c4c5d] px-7 py-12 text-white md:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[56px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><Eyebrow className="text-white/55">Primera definición</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-medium leading-tight tracking-[-0.045em] md:text-5xl">Cuéntanos qué población, servicio o resultado necesita comprenderse y qué decisión está pendiente.</h2></div><div className="flex flex-wrap gap-3"><Button href="/diagnostico?from=/analisis-datos-politicas-sociales" analyticsEvent="cta_click" analyticsTarget="social-policy-hub:scope" variant="secondary" className="rounded-full border-white bg-white text-ink">Diseñar un alcance</Button><Button href="/contact?interest=politicas-sociales&from=/analisis-datos-politicas-sociales" analyticsEvent="cta_click" analyticsTarget="social-policy-hub:contact" variant="ghost" className="!text-white/70 hover:!text-white">Plantear el encargo</Button></div></div></div></Container></Section>
    </>
  );
}
