import { ArrowRight, Building2, ClipboardCheck, Droplets, Leaf, MapPinned, ScanSearch } from "lucide-react";
import NextLink from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { Accordion, Button, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { breadcrumbJsonLd, buildMetadata, faqJsonLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";

const path = "/analisis-datos-gestion-ambiental";

export const metadata = buildMetadata({
  title: "Análisis de datos para la gestión ambiental",
  description: "Diagnósticos, líneas de base, monitoreo, observatorios y seguimiento de fiscalización ambiental para gobiernos, empresas y territorios del Perú.",
  path
});

const decisions = [
  { icon: ScanSearch, title: "Diagnosticar presiones y exposición", question: "¿Qué fuente afecta qué componente, población, ecosistema o actividad?", use: "Diagnóstico ambiental, línea de base, sitios críticos, pasivos, conflictos y salud ambiental." },
  { icon: Building2, title: "Ordenar la gobernanza", question: "¿Qué competencia, instrumento, actor y coordinación corresponden al problema?", use: "SLGA, SRGA, CAM, CAR, prioridades ambientales, roles y hoja de ruta institucional." },
  { icon: Droplets, title: "Monitorear calidad y cambio", question: "¿Qué variable, punto, método y frecuencia permiten detectar una variación relevante?", use: "Agua, aire, suelo, ruido, biodiversidad, emisiones, vertimientos y alertas territoriales." },
  { icon: ClipboardCheck, title: "Focalizar fiscalización", question: "¿Qué riesgo o incumplimiento justifica una acción y cómo se cierra el caso?", use: "PLANEFA, denuncias, supervisión, medidas correctivas, expedientes y seguimiento de obligaciones." },
  { icon: MapPinned, title: "Priorizar y evaluar respuestas", question: "¿Qué intervención reduce presión o exposición y cómo se verificará el resultado?", use: "Cartera ambiental, remediación, restauración, inversión, compromisos y evaluación de resultados." }
];

const evidenceChain = [
  { number: "01", title: "Presión", text: "Actividad, evento o proceso capaz de modificar el ambiente." },
  { number: "02", title: "Fuente", text: "Origen, ubicación, responsable, intensidad, duración y evidencia disponible." },
  { number: "03", title: "Receptor", text: "Población, ecosistema, recurso, activo o actividad potencialmente afectada." },
  { number: "04", title: "Competencia", text: "Autoridad, instrumento, obligación, coordinación y límite de actuación." },
  { number: "05", title: "Respuesta", text: "Monitoreo, prevención, fiscalización, corrección, restauración o información." },
  { number: "06", title: "Resultado", text: "Cambio ambiental o reducción de exposición con método y evidencia verificables." }
];

const evidence = [
  { label: "Datos municipales", title: "Gestión ambiental en DataPerú", text: "Oficinas e instrumentos municipales declarados en RENAMU 2025.", href: "/dataperu/temas/gestion-ambiental" },
  { label: "TDR + plantilla", title: "Contratar el análisis", text: "Presiones, monitoreo, competencias, fiscalización y aceptación verificable.", href: "/toolkits/tdr-analisis-gestion-ambiental" },
  { label: "Territorio", title: "Diagnóstico territorial", text: "Población, servicios, ambiente, capacidad institucional y prioridades.", href: "/diagnostico-territorial" },
  { label: "Sistema", title: "Observatorios y visores", text: "Indicadores, capas, alertas, responsables y operación sostenible.", href: "/observatorios-dashboards-visores" },
  { label: "Territorios", title: "Agendas departamentales", text: "Problemas, oportunidades, intervenciones y vacíos ambientales por departamento.", href: "/dataperu/departamentos" },
  { label: "Empresas", title: "Entorno e impacto", text: "Compromisos, riesgos territoriales, trazabilidad y evidencia para dirección.", href: "/solutions/monitoreo-entorno-impacto" }
];

const faq = [
  { title: "¿Pueden preparar un diagnóstico ambiental municipal o regional?", content: "Sí. Se delimita el problema, territorio, componente, población o ecosistema, competencias y fuentes disponibles. El diagnóstico debe separar evidencia observada, hipótesis y vacíos que requieren muestreo o estudio especializado." },
  { title: "¿Contar con una política o un plan demuestra buena gestión ambiental?", content: "No. El instrumento declarado muestra capacidad formal, pero no acredita vigencia, articulación, presupuesto, ejecución, fiscalización ni mejora ambiental. Es necesario seguir responsabilidades, acciones y resultados." },
  { title: "¿Pueden diseñar un observatorio ambiental?", content: "Sí. Debe comenzar por decisiones, usuarios, componentes, puntos, métodos, metadatos, umbrales y protocolos. Un visor que reúne capas sin control de calidad ni respuesta institucional no constituye un observatorio operativo." },
  { title: "¿Pueden apoyar un PLANEFA o la fiscalización ambiental?", content: "Podemos apoyar diagnóstico, priorización, estructura de datos, indicadores, programación y seguimiento dentro de las competencias aplicables. La autoridad conserva la conducción, actuación, debido procedimiento y decisiones de fiscalización." },
  { title: "¿Pueden integrar monitoreos de agua, aire, suelo o ruido?", content: "Sí, siempre que se documenten método, ubicación, fecha, unidad, límite de cuantificación, laboratorio, cadena de custodia y control de calidad. Integrar archivos no corrige por sí mismo diferencias de diseño o comparabilidad." },
  { title: "¿Trabajan también con empresas y compromisos socioambientales?", content: "Sí. Podemos estructurar líneas de base, tableros de compromisos, seguimiento de entorno y protocolos de evidencia. El alcance no sustituye obligaciones legales, instrumentos de gestión ambiental ni auditorías o estudios acreditados." }
];

export default function EnvironmentalManagementDataPage() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd([{ name: "Inicio", path: "/" }, { name: "Análisis de datos para gestión ambiental", path }])} />
      <JsonLd data={faqJsonLd(faq)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Service", name: "Análisis de datos para la gestión ambiental", description: "Diagnósticos, líneas de base, monitoreo, observatorios y seguimiento ambiental para gobiernos y empresas.", url: `${siteConfig.url}${path}`, provider: { "@type": "Organization", name: "NOAM", url: siteConfig.url }, areaServed: { "@type": "Country", name: "Perú" } }} />

      <section className="overflow-hidden bg-[#1f2921] pb-16 pt-14 text-white md:pb-24 md:pt-20"><Container><div className="grid gap-12 lg:grid-cols-[1fr_0.46fr] lg:items-end lg:gap-20"><div><Eyebrow className="text-[#bdcbaa]">Ambiente, evidencia y territorio</Eyebrow><Heading as="h1" size="display" className="max-w-[15ch] text-white">Tener una política y un plan no demuestra mejora ambiental.</Heading></div><div><p className="text-base leading-8 text-white/68">Conectamos presiones, monitoreo, población, ecosistemas, competencias y respuestas para priorizar, fiscalizar y evaluar con evidencia trazable.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="#decisiones" variant="secondary" className="rounded-full border-white bg-white text-ink">Definir la necesidad</Button><Button href="/toolkits/tdr-analisis-gestion-ambiental" variant="ghost" className="!text-white/70 hover:!text-white">Abrir TDR y plantilla</Button></div></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-md border border-white/12 bg-white/12 sm:grid-cols-3">{["Gobiernos, empresas y ciudadanía", "Calidad, fiscalización y resultados", "Fuentes oficiales, monitoreo y campo"].map((item, index) => <div key={item} className="bg-[#29352b] p-6 md:p-8"><span className="font-mono text-[10px] text-[#bdcbaa]">0{index + 1}</span><p className="mt-9 max-w-[27ch] text-lg font-medium leading-6 tracking-[-0.02em] text-white/86">{item}</p></div>)}</div></Container></section>

      <Section id="decisiones"><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Qué necesitas decidir</Eyebrow><Heading size="xl">Cinco decisiones que un instrumento aislado no resuelve.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">La gestión comienza al formular la prioridad, pero solo se completa cuando la evidencia activa una respuesta y permite verificar un cambio.</p></div><div className="mt-12 divide-y divide-border border-y border-border">{decisions.map(({ icon: Icon, title, question, use }, index) => <article key={title} className="grid gap-6 py-9 md:grid-cols-[64px_0.75fr_1fr] md:gap-10 md:py-11"><div className="flex items-center gap-4 md:block"><span className="font-mono text-[10px] text-[#62724d]">0{index + 1}</span><Icon className="h-5 w-5 text-[#62724d] md:mt-8" aria-hidden /></div><div><h2 className="text-2xl font-medium tracking-[-0.035em] text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/72">{question}</p></div><div><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">Aplicaciones</span><p className="mt-3 text-sm leading-7 text-ink/62">{use}</p></div></article>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-20"><div><Leaf className="h-5 w-5 text-[#62724d]" aria-hidden /><Eyebrow className="mt-6">Cadena de evidencia</Eyebrow><Heading size="xl">Del problema reportado al resultado ambiental.</Heading><p className="mt-5 text-sm leading-7 text-ink/65">La trazabilidad evita confundir una percepción, una medición, un incumplimiento y un impacto.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{evidenceChain.map((item) => <article key={item.number} className="min-h-[190px] bg-canvas p-6 md:p-8"><span className="font-mono text-[10px] text-[#62724d]">{item.number}</span><h2 className="mt-9 text-xl font-medium tracking-[-0.025em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p></article>)}</div></div></Container></Section>

      <Section className="border-b border-border bg-[#e5e9df]"><Container><div className="grid gap-10 lg:grid-cols-[0.46fr_1fr] lg:gap-20"><div><Eyebrow>Marco y fuentes</Eyebrow><Heading size="xl">La institución organiza; la medición y la respuesta demuestran capacidad.</Heading></div><div className="max-w-3xl space-y-5 text-base leading-8 text-ink/72"><p>MINAM actualizó guías para los sistemas locales y regionales de gestión ambiental. OEFA reúne instrumentos para EFA locales, planificación PLANEFA y datos abiertos de evaluación y fiscalización. ANA integra información hídrica por cuenca, y las fuentes sectoriales completan cada componente.</p><p>DataPerú añade oficinas e instrumentos declarados por municipalidades en RENAMU 2025. Su existencia reportada no demuestra vigencia, calidad, ejecución, presupuesto, coordinación ni mejora ambiental.</p><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#566642]"><a href="https://www.gob.pe/institucion/minam/noticias/1168995-minam-aprueba-guia-que-prioriza-la-conservacion-ambiental-y-de-los-recursos-naturales-con-participacion-de-la-poblacion" target="_blank" rel="noreferrer">Sistema local de gestión ambiental</a><a href="https://www.gob.pe/institucion/minam/noticias/1105401-minam-aprueba-nueva-guia-para-fortalecer-la-gestion-ambiental-en-regiones" target="_blank" rel="noreferrer">Sistema regional</a><a href="https://www.gob.pe/institucion/oefa/campa%C3%B1as/144141-kit-para-la-fiscalizacion-ambiental-para-efa-locales" target="_blank" rel="noreferrer">Kit para EFA locales</a><a href="https://www.gob.pe/institucion/oefa/pages/15555-acceder-a-los-datos-abiertos-del-oefa" target="_blank" rel="noreferrer">Datos abiertos de OEFA</a><a href="https://www.gob.pe/institucion/ana/noticias/828913-ana-presenta-moderna-herramienta-tecnologica-observatorio-nacional-de-recursos-hidricos-para-la-gestion-integrada-de-recursos-hidricos" target="_blank" rel="noreferrer">Observatorio hídrico</a><NextLink href="/dataperu/temas/gestion-ambiental">Capacidades en DataPerú</NextLink></div></div></div></Container></Section>

      <Section><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Evidencia y servicios</Eyebrow><Heading size="xl">Explora antes de plantear el encargo.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Revisa capacidades municipales, agendas territoriales, método y sistemas que pueden combinarse según el problema ambiental.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{evidence.map((item) => <NextLink key={item.href} href={item.href} className="group min-h-[225px] bg-canvas p-6 transition-colors hover:bg-panel md:p-8"><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#62724d]">{item.label}</span><h2 className="mt-10 text-2xl font-medium tracking-[-0.035em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-ink">Abrir <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" aria-hidden /></span></NextLink>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container size="narrow"><Eyebrow>Preguntas frecuentes</Eyebrow><Heading size="xl">Antes de producir otro instrumento.</Heading><Accordion items={faq} className="mt-8" /></Container></Section>

      <Section className="pb-0"><Container><div className="relative overflow-hidden rounded-[1.5rem] bg-[#62724d] px-7 py-12 text-white md:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[56px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><Eyebrow className="text-white/55">Primera definición</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-medium leading-tight tracking-[-0.045em] md:text-5xl">Cuéntanos qué problema ambiental debe entenderse y qué decisión está pendiente.</h2></div><div className="flex flex-wrap gap-3"><Button href="/diagnostico?from=/analisis-datos-gestion-ambiental" analyticsEvent="cta_click" analyticsTarget="environment-hub:scope" variant="secondary" className="rounded-full border-white bg-white text-ink">Diseñar un alcance</Button><Button href="/contact?interest=gestion-ambiental&from=/analisis-datos-gestion-ambiental" analyticsEvent="cta_click" analyticsTarget="environment-hub:contact" variant="ghost" className="!text-white/70 hover:!text-white">Plantear el encargo</Button></div></div></div></Container></Section>
    </>
  );
}
