import { redirect } from "next/navigation";
import { Badge, Button, Card, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { getAdminPrincipal } from "@/lib/admin-auth";
import { getAdminUsers } from "@/lib/admin-identity";
import { createAdminUserAction, revokeAdminUserSessionsAction, updateAdminUserAction } from "./actions";

function date(value: string | null) { return value ? new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Nunca"; }

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ created?: string; updated?: string; error?: string }> }) {
  const [principal, params] = await Promise.all([getAdminPrincipal(), searchParams]);
  if (!principal?.userId || principal.role !== "owner") redirect("/admin");
  const users = await getAdminUsers();
  return <Section className="pt-14 md:pt-20"><Container><Button href="/admin/security" variant="ghost" className="mb-8">Volver a seguridad</Button><div className="grid gap-6 md:grid-cols-[1fr_0.55fr] md:items-end"><div><Eyebrow>NOAM OS · Accesos</Eyebrow><Heading as="h1" size="xl">Operadores y roles.</Heading></div><p className="text-sm leading-7 text-ink/65">Cada persona recibe una identidad propia. No compartas contraseñas ni crees cuentas genéricas.</p></div>
  {params.created || params.updated ? <p className="mt-8 rounded-sm border border-border bg-panel px-4 py-3 text-sm text-ink/70">Cambio registrado.</p> : null}{params.error ? <p role="alert" className="mt-8 rounded-sm border border-red-300 bg-red-50 px-4 py-3 text-sm text-red-800">No se pudo aplicar el cambio. Verifica los campos y conserva al menos un owner activo.</p> : null}
  <div className="mt-10 grid gap-8 lg:grid-cols-[0.42fr_1fr]"><Card><h2 className="text-xl font-medium text-ink">Nueva identidad</h2><form action={createAdminUserAction} className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-medium">Nombre<input name="displayName" required minLength={2} className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label><label className="grid gap-2 text-sm font-medium">Email<input name="email" type="email" required className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label><label className="grid gap-2 text-sm font-medium">Rol<select name="role" defaultValue="analyst" className="min-h-11 rounded-sm border border-border bg-canvas px-3"><option value="analyst">Analyst</option><option value="editor">Editor</option><option value="owner">Owner</option></select></label><label className="grid gap-2 text-sm font-medium">Contraseña temporal<input name="temporaryPassword" type="password" required minLength={14} maxLength={128} autoComplete="new-password" className="min-h-11 rounded-sm border border-border bg-canvas px-3" /></label><p className="text-xs leading-5 text-muted">Comunícala por un canal separado. El operador debe cambiarla y activar MFA al ingresar.</p><Button type="submit">Crear identidad</Button></form></Card>
  <div className="space-y-4">{users.map((user) => <Card key={user.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge>{user.role}</Badge><Badge>{user.status}</Badge><Badge>{user.mfaEnabledAt ? "MFA activo" : "MFA pendiente"}</Badge>{user.id === principal.userId ? <Badge>tú</Badge> : null}</div><h2 className="mt-4 text-lg font-medium text-ink">{user.displayName}</h2><p className="mt-1 text-sm text-muted">{user.email}</p><p className="mt-3 text-xs text-muted">Último acceso: {date(user.lastLoginAt)}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><form action={updateAdminUserAction} className="flex flex-wrap gap-2"><input type="hidden" name="userId" value={user.id} /><select name="role" defaultValue={user.role} className="min-h-10 rounded-sm border border-border bg-canvas px-3 text-sm"><option value="analyst">Analyst</option><option value="editor">Editor</option><option value="owner">Owner</option></select><select name="status" defaultValue={user.status} className="min-h-10 rounded-sm border border-border bg-canvas px-3 text-sm"><option value="active">Activo</option><option value="suspended">Suspendido</option></select><Button type="submit" variant="secondary">Actualizar</Button></form><form action={revokeAdminUserSessionsAction}><input type="hidden" name="userId" value={user.id} /><Button type="submit" variant="ghost">Revocar sesiones</Button></form></div></Card>)}</div></div></Container></Section>;
}
