import { Accessibility, ArrowRight, BusFront, ChartNoAxesCombined, MapPinned, Route, ShieldCheck } from "lucide-react";
import NextLink from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { Accordion, Button, Container, Eyebrow, Heading, Section } from "@/components/ui";
import { breadcrumbJsonLd, buildMetadata, faqJsonLd } from "@/lib/seo";
import { siteConfig } from "@/lib/site-config";

const path = "/analisis-datos-movilidad-transporte";

export const metadata = buildMetadata({
  title: "Análisis de datos para movilidad y transporte",
  description: "Diagnósticos, encuestas, planes de movilidad, observatorios, seguridad vial y evaluación del transporte urbano para gobiernos y empresas del Perú.",
  path
});

const decisions = [
  { icon: Route, title: "Comprender los desplazamientos", question: "¿Quién viaja, desde dónde, hacia dónde, cuándo, por qué medio y con qué barrera?", use: "Encuestas origen-destino, aforos, telefonía agregada, accesibilidad, tiempos y demanda." },
  { icon: BusFront, title: "Rediseñar el servicio", question: "¿Qué oferta, ruta, frecuencia, integración y regulación responden a la demanda?", use: "Transporte público, sistemas integrados, paraderos, flota, informalidad y sostenibilidad financiera." },
  { icon: ShieldCheck, title: "Reducir riesgo vial", question: "¿Dónde, cómo y para quién se concentra el riesgo y qué medida puede reducirlo?", use: "Siniestros, velocidad, intersecciones, zonas escolares, corredores, peatones y motociclistas." },
  { icon: Accessibility, title: "Mejorar acceso y equidad", question: "¿Quién pierde tiempo, seguridad u oportunidades por cómo funciona la movilidad?", use: "Mujeres, cuidados, discapacidad, niñez, periferias, caminata, bicicleta y acoso en transporte." },
  { icon: ChartNoAxesCombined, title: "Priorizar y evaluar", question: "¿Qué gestión, infraestructura o piloto produce el mayor cambio verificable?", use: "PMUS, cartera, semaforización, tráfico calmado, espacio público, logística y evaluación antes-después." }
];

const evidenceChain = [
  { number: "01", title: "Personas", text: "Población, actividades, necesidades, vulnerabilidades y capacidad de pago." },
  { number: "02", title: "Viajes", text: "Origen, destino, motivo, hora, modo, transbordo, duración y variabilidad." },
  { number: "03", title: "Red", text: "Vías, veredas, ciclovías, paraderos, intersecciones, barreras y capacidad." },
  { number: "04", title: "Servicio", text: "Rutas, frecuencia, flota, ocupación, confiabilidad, tarifa y operación." },
  { number: "05", title: "Experiencia", text: "Tiempo, seguridad, accesibilidad, comodidad, violencia, costo y reclamo." },
  { number: "06", title: "Resultado", text: "Acceso, seguridad, emisiones, productividad, equidad y calidad urbana." }
];

const evidence = [
  { label: "Marco nacional", title: "Política de transporte urbano", text: "Objetivos sobre sistemas eficaces, gobernanza, infraestructura y necesidades de movilidad.", href: "https://www.gob.pe/institucion/mtc/informes-publicaciones/366455-politica-nacional-de-transporte-urbano-2019" },
  { label: "TDR + plantilla", title: "Contratar el análisis", text: "Veinte bloques para demanda, oferta, seguridad, accesibilidad, intervención y conformidad.", href: "/toolkits/tdr-analisis-movilidad-transporte" },
  { label: "Seguridad vial", title: "Observatorio nacional", text: "Información intersectorial, georreferenciada y estandarizada sobre siniestros y víctimas.", href: "https://www.gob.pe/institucion/mtc/noticias/776354-observatorio-nacional-de-seguridad-vial-del-mtc-consolida-informacion-para-proteger-la-vida-de-los-ciudadanos" },
  { label: "Muestra", title: "Diagnóstico de un servicio", text: "Arquitectura demostrativa para separar demanda, acceso, operación y resultado.", href: "/muestras/diagnostico-desempeno-servicio-publico" },
  { label: "Sistema", title: "Observatorios y visores", text: "Indicadores, capas, alertas, protocolos y operación sostenible.", href: "/observatorios-dashboards-visores" },
  { label: "Evaluación", title: "Línea de base y resultados", text: "Diseños para medir cambios de tiempo, seguridad, acceso, demanda o experiencia.", href: "/linea-base-evaluacion-impacto" }
];

const faq = [
  { title: "¿Pueden preparar un diagnóstico o plan de movilidad?", content: "Sí. Se delimita la ciudad, área funcional, decisiones, actores, población, viajes, redes, servicios, seguridad y datos disponibles. Un PMUS requiere además conducción institucional, participación, visión, cartera y articulación con desarrollo urbano e inversiones." },
  { title: "¿Un aforo vehicular basta para explicar la movilidad?", content: "No. El aforo describe flujo en un punto y periodo. Debe relacionarse con viajes, motivos, modos, tiempos, peatones, transporte público, uso del suelo, variabilidad y población afectada según la decisión." },
  { title: "¿Pueden diseñar un observatorio de movilidad?", content: "Sí. Debe definir decisiones, usuarios, fuentes, indicadores, geografía, frecuencia, umbrales y responsables. También requiere protocolos de actualización y respuesta; acumular mapas o gráficos no garantiza operación." },
  { title: "¿Pueden analizar seguridad vial?", content: "Sí. Podemos integrar siniestros, víctimas, infraestructura, velocidad, exposición y observación de campo para priorizar lugares y medidas. Los registros deben conciliar fuentes y distinguir siniestro, persona, severidad y periodo." },
  { title: "¿Pueden hacer encuestas de movilidad o satisfacción?", content: "Sí. Diseñamos muestras, instrumentos, trabajo de campo, ponderación y análisis para viajes, experiencia, accesibilidad o percepción. La inferencia debe respetar la población y el diseño muestral." },
  { title: "¿Trabajan con empresas y operadores?", content: "Sí. Podemos analizar demanda, localización, logística urbana, rutas, flota, experiencia, accesibilidad e impactos territoriales. El servicio no sustituye habilitaciones, ingeniería especializada ni decisiones regulatorias de la autoridad competente." }
];

export default function MobilityTransportDataPage() {
  return (
    <>
      <JsonLd data={breadcrumbJsonLd([{ name: "Inicio", path: "/" }, { name: "Análisis de datos para movilidad y transporte", path }])} />
      <JsonLd data={faqJsonLd(faq)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Service", name: "Análisis de datos para movilidad y transporte", description: "Diagnósticos, encuestas, observatorios, seguridad vial y evaluación de movilidad para gobiernos y empresas.", url: `${siteConfig.url}${path}`, provider: { "@type": "Organization", name: "NOAM", url: siteConfig.url }, areaServed: { "@type": "Country", name: "Perú" } }} />

      <section className="overflow-hidden bg-[#272b36] pb-16 pt-14 text-white md:pb-24 md:pt-20"><Container><div className="grid gap-12 lg:grid-cols-[1fr_0.46fr] lg:items-end lg:gap-20"><div><Eyebrow className="text-[#bcc5dc]">Movilidad, acceso y ciudad</Eyebrow><Heading as="h1" size="display" className="max-w-[14ch] text-white">Contar vehículos no explica cómo se mueve una ciudad.</Heading></div><div><p className="text-base leading-8 text-white/68">Conectamos personas, viajes, redes, servicios y seguridad para priorizar acciones que reduzcan tiempo, riesgo y exclusión.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="#decisiones" variant="secondary" className="rounded-full border-white bg-white text-ink">Definir la necesidad</Button><Button href="/toolkits/tdr-analisis-movilidad-transporte" variant="ghost" className="!text-white/70 hover:!text-white">Abrir TDR y plantilla</Button></div></div></div><div className="mt-16 grid gap-px overflow-hidden rounded-md border border-white/12 bg-white/12 sm:grid-cols-3">{["Gobiernos, operadores y ciudadanía", "Viajes, servicio y seguridad", "Datos, participación y observación"].map((item, index) => <div key={item} className="bg-[#333947] p-6 md:p-8"><span className="font-mono text-[10px] text-[#bcc5dc]">0{index + 1}</span><p className="mt-9 max-w-[27ch] text-lg font-medium leading-6 tracking-[-0.02em] text-white/86">{item}</p></div>)}</div></Container></section>

      <Section id="decisiones"><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Qué necesitas decidir</Eyebrow><Heading size="xl">Cinco decisiones que un mapa de tráfico no resuelve.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">La movilidad se mide desde la capacidad de las personas para acceder a oportunidades, no solo desde la velocidad de los vehículos.</p></div><div className="mt-12 divide-y divide-border border-y border-border">{decisions.map(({ icon: Icon, title, question, use }, index) => <article key={title} className="grid gap-6 py-9 md:grid-cols-[64px_0.75fr_1fr] md:gap-10 md:py-11"><div className="flex items-center gap-4 md:block"><span className="font-mono text-[10px] text-[#657296]">0{index + 1}</span><Icon className="h-5 w-5 text-[#657296] md:mt-8" aria-hidden /></div><div><h2 className="text-2xl font-medium tracking-[-0.035em] text-ink">{title}</h2><p className="mt-4 text-sm leading-7 text-ink/72">{question}</p></div><div><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted">Aplicaciones</span><p className="mt-3 text-sm leading-7 text-ink/62">{use}</p></div></article>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container><div className="grid gap-12 lg:grid-cols-[0.42fr_1fr] lg:gap-20"><div><MapPinned className="h-5 w-5 text-[#657296]" aria-hidden /><Eyebrow className="mt-6">Cadena de evidencia</Eyebrow><Heading size="xl">De la necesidad de viajar al resultado urbano.</Heading><p className="mt-5 text-sm leading-7 text-ink/65">Cada eslabón evita atribuir a una obra, ruta o restricción un efecto que no se midió.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2">{evidenceChain.map((item) => <article key={item.number} className="min-h-[190px] bg-canvas p-6 md:p-8"><span className="font-mono text-[10px] text-[#657296]">{item.number}</span><h2 className="mt-9 text-xl font-medium tracking-[-0.025em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p></article>)}</div></div></Container></Section>

      <Section className="border-b border-border bg-[#e7e9ef]"><Container><div className="grid gap-10 lg:grid-cols-[0.46fr_1fr] lg:gap-20"><div><Eyebrow>Marco y fuentes</Eyebrow><Heading size="xl">La ciudad real exige combinar registros y observación.</Heading></div><div className="max-w-3xl space-y-5 text-base leading-8 text-ink/72"><p>La Política Nacional de Transporte Urbano organiza objetivos de servicio, gobernanza, infraestructura y necesidades de desplazamiento. Promovilidad acompaña a municipalidades provinciales en planificación y gestión; el ONSV integra registros de siniestros y herramientas georreferenciadas.</p><p>Ninguna fuente aislada representa todos los viajes. Aforos, GPS, tarjetas, encuestas, siniestros, licencias y observación tienen sesgos, coberturas y unidades distintas. La integración debe conservar fecha, modo, geografía, población y método.</p><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-[#596684]"><a href="https://www.gob.pe/institucion/mtc/informes-publicaciones/366455-politica-nacional-de-transporte-urbano-2019" target="_blank" rel="noreferrer">Política nacional</a><a href="https://www.gob.pe/institucion/promovilidad/institucional" target="_blank" rel="noreferrer">Promovilidad</a><a href="https://www.gob.pe/institucion/mtc/noticias/1417565-mtc-impulsa-sistemas-integrados-de-transporte-mediante-los-planes-de-movilidad-urbana-sostenible" target="_blank" rel="noreferrer">PMUS 2026</a><a href="https://www.gob.pe/institucion/mtc/noticias/776354-observatorio-nacional-de-seguridad-vial-del-mtc-consolida-informacion-para-proteger-la-vida-de-los-ciudadanos" target="_blank" rel="noreferrer">ONSV</a><a href="https://www.gob.pe/institucion/mtc/campa%C3%B1as/130605-entornos-viales-seguros" target="_blank" rel="noreferrer">Entornos viales seguros</a></div></div></div></Container></Section>

      <Section><Container><div className="grid gap-8 md:grid-cols-[0.55fr_1fr] md:items-end"><div><Eyebrow>Evidencia y servicios</Eyebrow><Heading size="xl">Explora antes de plantear el encargo.</Heading></div><p className="max-w-2xl text-sm leading-7 text-ink/65 md:justify-self-end">Combina marco, seguridad vial, contexto territorial, sistemas y evaluación según la decisión de movilidad.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{evidence.map((item) => <NextLink key={item.href} href={item.href} className="group min-h-[225px] bg-canvas p-6 transition-colors hover:bg-panel md:p-8" {...(item.href.startsWith("http") ? { target: "_blank", rel: "noreferrer" } : {})}><span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#657296]">{item.label}</span><h2 className="mt-10 text-2xl font-medium tracking-[-0.035em] text-ink">{item.title}</h2><p className="mt-3 text-sm leading-6 text-ink/62">{item.text}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-ink">Abrir <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" aria-hidden /></span></NextLink>)}</div></Container></Section>

      <Section className="border-y border-border bg-panel/45"><Container size="narrow"><Eyebrow>Preguntas frecuentes</Eyebrow><Heading size="xl">Antes de intervenir la ciudad.</Heading><Accordion items={faq} className="mt-8" /></Container></Section>

      <Section className="pb-0"><Container><div className="relative overflow-hidden rounded-[1.5rem] bg-[#596684] px-7 py-12 text-white md:px-12 md:py-16"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full border-[56px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><Eyebrow className="text-white/55">Primera definición</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-medium leading-tight tracking-[-0.045em] md:text-5xl">Cuéntanos qué desplazamiento, servicio o zona debe mejorar y qué decisión está pendiente.</h2></div><div className="flex flex-wrap gap-3"><Button href="/diagnostico?from=/analisis-datos-movilidad-transporte" analyticsEvent="cta_click" analyticsTarget="mobility-hub:scope" variant="secondary" className="rounded-full border-white bg-white text-ink">Diseñar un alcance</Button><Button href="/contact?interest=movilidad-transporte&from=/analisis-datos-movilidad-transporte" analyticsEvent="cta_click" analyticsTarget="mobility-hub:contact" variant="ghost" className="!text-white/70 hover:!text-white">Plantear el encargo</Button></div></div></div></Container></Section>
    </>
  );
}
